### ISSUE TITLE
Open fixes after 2.0

### ISSUE THREAD

**Issue by sstroemer** [ait-energy/IESopt.jl#30]
Updated list of open points to fix/clarify after discussion on 12.11., in addition to all points in [this comment](https://github.com/ait-energy/IESopt.jl/pull/20#issuecomment-2458499239):

**todos:**

- [x] virtuals without functions do not get their parameters (see parse.jl Line 65)
- [ ] replace meta.parse in templates by JuliaSyntax
- [ ] implement "validate: my_valid.jl" instead of writing code in strings
- [x] check/fix that "tag vererbung" does not work for container templates (bess is no householde)
- [ ] document that addons should now return true/false
- [ ] document the weird regex in _string_to_fevalexpr
- [ ] update the "breaking changes" list
- [ ] compile a "new features" list
- [ ] create a "how to update to 2.0" list

**notes:**

- [ ] document tags (and their casing), including auto-tagging feature

**test:**

- [ ] loaded module in main that has dependency that IESopt does not have (timezones.jl)
